#!/usr/bin/python3


import serial
import time
from datetime import datetime


################################################################################
################################################################################
################################################################################
ser = serial.Serial()
ser.port = '/dev/ttyUSB0'
ser.baudrate = 9600
ser.bytesize = serial.SEVENBITS
ser.parity = serial.PARITY_EVEN
ser.stopbits = serial.STOPBITS_ONE
ser.timeout = 5  # read timeout in seconds
#ser.rtscts = 0
ser.dsrdtr = True

ser.open()
print(ser.name, ser.is_open)


time.sleep(0.5)
if (ser.isOpen() == True):
    ser.write('SYST:REM\n'.encode())  # note that this should only be run once
    print("Serial open")
#    return ser #Return ser as a handler
#else:
#    return False   

ser.write('*IDN?\n'.encode('ascii'))
text = ser.readline()
print(text)

#Voltage DC - Range AUTO
#ser.write("CONF:VOLT:DC AUTO\n".encode())
#
#ser.write("READ?\n".encode())
#text = ser.readline()
#print(f'reading: {text}')

for i in range(10):
    ser.write('MEAS:VOLT:DC? 10,0.003\n'.encode())
    text = ser.readline()
    current_time = datetime.utcnow().strftime('%F %T.%f')[:-3]
    print(current_time, text)
    time.sleep(10)

#ser.write(b'hello')
#text = ser.read()
#print(text)

ser.close()
print('Serial closed')
print(ser.is_open)


################################################################################
################################################################################
################################################################################
